server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice-db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
